sudo: required
services:
  - docker

before_install:
  - docker build -t egbodofo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true egbodofo/react-test npm test -- --coverage

after_success:
  # build docker images
  - docker build -t egbodofo/ecodock-client ./client
  - docker build -t egbodofo/ecodock-nginx ./nginx
  - docker build -t egbodofo/ecodock-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these build images and push to docker hub
  - docker push egbodofo/ecodock-client
  - docker push egbodofo/ecodock-nginx
  - docker push egbodofo/ecodock-server
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: wishmart
#   env: Wishmart-env
#   bucket_name: elasticbeanstalk-us-east-2-008951252297
#   bucket_path: wishmart
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
