version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  ngnix:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PORT=4000
      - MONGODB_URL=mongodb://mongo:27017/docker-ecommerce
      - JWT_SECRET=ecommercedockerjwtsecret
    depends_on:
      - mongo
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
# push and test again
